In [ ]:
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
endpoint = '/content/drive/MyDrive/Leak_detection_code/Hanoi_CMH'

In [ ]:
df = pd.read_csv(f"{endpoint}/Final_csv_file2.csv")

In [ ]:
df

,Unnamed: 0,Timestamp,Scenario,D_node-1,P_Node-1,F_Link-1,Leak_Node-1,D_node-2,P_Node-2,F_Link-2,...,D_node-31,P_Node-31,F_Link-31,Leak_Node-31,D_node-32,P_Node-32,F_Link-32,Leak_Node-32,F_Link-33,F_Link-34
0,0,01-01-2017 00:00,1,-3405.6,0.0,3405.6,0,147.6,69.901,3261.6,...,14.4,66.433,25.2,0,144.0,66.458,-36.0,0,54.0,198.0
1,1,01-01-2017 00:30,1,-2970.0,0.0,2970.0,0,154.8,69.923,2811.6,...,14.4,67.274,21.6,0,122.4,67.295,-32.4,0,46.8,169.2
2,2,01-01-2017 01:00,1,-2656.8,0.0,2656.8,0,126.0,69.937,2530.8,...,10.8,67.758,18.0,0,126.0,67.769,-21.6,0,32.4,158.4
3,3,01-01-2017 01:30,1,-2401.2,0.0,2401.2,0,108.0,69.948,2289.6,...,10.8,68.132,18.0,0,108.0,68.146,-25.2,0,36.0,144.0
4,4,01-01-2017 02:00,1,-2199.6,0.0,2199.6,0,111.6,69.956,2088.0,...,10.8,68.417,14.4,0,100.8,68.426,-21.6,0,32.4,133.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175195,175195,31-12-2017 21:30,10,-5554.8,0.0,5554.8,0,237.6,69.811,5317.2,...,28.8,63.217,57.6,0,230.4,63.248,-39.6,0,68.4,298.8
175196,175196,31-12-2017 22:00,10,-5252.4,0.0,5252.4,0,216.0,69.830,5040.0,...,28.8,63.890,50.4,0,208.8,63.923,-43.2,0,72.0,280.8
175197,175197,31-12-2017 22:30,10,-4906.8,0.0,4906.8,0,219.6,69.850,4687.2,...,25.2,64.521,46.8,0,201.6,64.547,-39.6,0,61.2,266.4
175198,175198,31-12-2017 23:00,10,-4572.0,0.0,4572.0,0,198.0,69.869,4370.4,...,21.6,65.291,46.8,0,187.2,65.309,-28.8,0,50.4,237.6
175199,175199,31-12-2017 23:30,10,-4107.6,0.0,4107.6,0,180.0,69.892,3927.6,...,18.0,66.141,43.2,0,165.6,66.156,-28.8,0,46.8,212.4

# Adding Leak column

In [ ]:
lcols=[]
for i in range(32):
	col= f'Leak_Node-{i+1}'
	lcols.append(col)
lcols

['Leak_Node-1',
 'Leak_Node-2',
 'Leak_Node-3',
 'Leak_Node-4',
 'Leak_Node-5',
 'Leak_Node-6',
 'Leak_Node-7',
 'Leak_Node-8',
 'Leak_Node-9',
 'Leak_Node-10',
 'Leak_Node-11',
 'Leak_Node-12',
 'Leak_Node-13',
 'Leak_Node-14',
 'Leak_Node-15',
 'Leak_Node-16',
 'Leak_Node-17',
 'Leak_Node-18',
 'Leak_Node-19',
 'Leak_Node-20',
 'Leak_Node-21',
 'Leak_Node-22',
 'Leak_Node-23',
 'Leak_Node-24',
 'Leak_Node-25',
 'Leak_Node-26',
 'Leak_Node-27',
 'Leak_Node-28',
 'Leak_Node-29',
 'Leak_Node-30',
 'Leak_Node-31',
 'Leak_Node-32']

In [ ]:
def leak_detect(sum):
    if(sum==0):
        return 0
    else:
        return 1

df['Leak']=df[lcols].sum(axis=1).apply(lambda x: leak_detect(x))

In [ ]:
df

,Unnamed: 0,Timestamp,Scenario,D_node-1,P_Node-1,F_Link-1,Leak_Node-1,D_node-2,P_Node-2,F_Link-2,...,P_Node-31,F_Link-31,Leak_Node-31,D_node-32,P_Node-32,F_Link-32,Leak_Node-32,F_Link-33,F_Link-34,Leak
0,0,01-01-2017 00:00,1,-3405.6,0.0,3405.6,0,147.6,69.901,3261.6,...,66.433,25.2,0,144.0,66.458,-36.0,0,54.0,198.0,0
1,1,01-01-2017 00:30,1,-2970.0,0.0,2970.0,0,154.8,69.923,2811.6,...,67.274,21.6,0,122.4,67.295,-32.4,0,46.8,169.2,0
2,2,01-01-2017 01:00,1,-2656.8,0.0,2656.8,0,126.0,69.937,2530.8,...,67.758,18.0,0,126.0,67.769,-21.6,0,32.4,158.4,0
3,3,01-01-2017 01:30,1,-2401.2,0.0,2401.2,0,108.0,69.948,2289.6,...,68.132,18.0,0,108.0,68.146,-25.2,0,36.0,144.0,0
4,4,01-01-2017 02:00,1,-2199.6,0.0,2199.6,0,111.6,69.956,2088.0,...,68.417,14.4,0,100.8,68.426,-21.6,0,32.4,133.2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175195,175195,31-12-2017 21:30,10,-5554.8,0.0,5554.8,0,237.6,69.811,5317.2,...,63.217,57.6,0,230.4,63.248,-39.6,0,68.4,298.8,0
175196,175196,31-12-2017 22:00,10,-5252.4,0.0,5252.4,0,216.0,69.830,5040.0,...,63.890,50.4,0,208.8,63.923,-43.2,0,72.0,280.8,0
175197,175197,31-12-2017 22:30,10,-4906.8,0.0,4906.8,0,219.6,69.850,4687.2,...,64.521,46.8,0,201.6,64.547,-39.6,0,61.2,266.4,0
175198,175198,31-12-2017 23:00,10,-4572.0,0.0,4572.0,0,198.0,69.869,4370.4,...,65.291,46.8,0,187.2,65.309,-28.8,0,50.4,237.6,0
175199,175199,31-12-2017 23:30,10,-4107.6,0.0,4107.6,0,180.0,69.892,3927.6,...,66.141,43.2,0,165.6,66.156,-28.8,0,46.8,212.4,0

In [ ]:
df['Leak'].max()

1

# Removing unwanted columns

In [ ]:
df.drop(['Unnamed: 0', 'Timestamp', 'Scenario'], axis=1, inplace=True)

# Normalising

In [ ]:
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = float(df[feature_name].max())
        min_value = float(df[feature_name].min())
        df[feature_name].apply(lambda x: float(x))
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [ ]:
df_normalized = normalize(df)

In [ ]:
df_normalized

,D_node-1,P_Node-1,F_Link-1,Leak_Node-1,D_node-2,P_Node-2,F_Link-2,Leak_Node-2,D_node-3,P_Node-3,...,P_Node-31,F_Link-31,Leak_Node-31,D_node-32,P_Node-32,F_Link-32,Leak_Node-32,F_Link-33,F_Link-34,Leak
0,0.848724,NaN,0.151276,NaN,0.181159,0.961435,0.147599,NaN,0.166667,0.911553,...,0.917526,0.867925,NaN,0.200000,0.913288,0.932099,NaN,0.074713,0.113636,0.0
1,0.894144,NaN,0.105856,NaN,0.195652,0.973219,0.098790,NaN,0.103175,0.936695,...,0.942458,0.861635,NaN,0.150000,0.939471,0.938272,NaN,0.063218,0.083333,0.0
2,0.926802,NaN,0.073198,NaN,0.137681,0.980718,0.068333,NaN,0.087302,0.950994,...,0.956807,0.855346,NaN,0.158333,0.954298,0.956790,NaN,0.040230,0.071970,0.0
3,0.953453,NaN,0.046547,NaN,0.101449,0.986610,0.042171,NaN,0.063492,0.962074,...,0.967894,0.855346,NaN,0.116667,0.966091,0.950617,NaN,0.045977,0.056818,0.0
4,0.974474,NaN,0.025526,NaN,0.108696,0.990894,0.020305,NaN,0.055556,0.970644,...,0.976343,0.849057,NaN,0.100000,0.974850,0.956790,NaN,0.040230,0.045455,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175195,0.624625,NaN,0.375375,NaN,0.362319,0.913230,0.370558,NaN,0.404762,0.914441,...,0.822187,0.924528,NaN,0.400000,0.812875,0.925926,NaN,0.097701,0.219697,0.0
175196,0.656156,NaN,0.343844,NaN,0.318841,0.923407,0.340492,NaN,0.365079,0.924195,...,0.842138,0.911950,NaN,0.350000,0.833990,0.919753,NaN,0.103448,0.200758,0.0
175197,0.692192,NaN,0.307808,NaN,0.326087,0.934119,0.302226,NaN,0.293651,0.935748,...,0.860844,0.905660,NaN,0.333333,0.853510,0.925926,NaN,0.086207,0.185606,0.0
175198,0.727102,NaN,0.272898,NaN,0.282609,0.944296,0.267864,NaN,0.277778,0.945597,...,0.883671,0.905660,NaN,0.300000,0.877346,0.944444,NaN,0.068966,0.155303,0.0
175199,0.775526,NaN,0.224474,NaN,0.246377,0.956615,0.219836,NaN,0.238095,0.958428,...,0.908870,0.899371,NaN,0.250000,0.903841,0.944444,NaN,0.063218,0.128788,0.0

In [ ]:
df_normalized['Leak'].max()

1.0

# Exporting a normalised dataframe

In [ ]:
# df_normalized.to_csv(f'{endpoint}/normalised_csv_file.csv')